### ISSUE TITLE
'multiple()' func in tag.go does not take into account the maximum packet size

### ISSUE THREAD

**Issue by lly-c232733** [loki-os/go-ethernet-ip#11]
In the case that a large tag group is created in which a request length (in bytes) exceeds the maximum CIP packet length, the request cannot be fulfilled. Max lengths are as follows: 500 bytes for unconnected message (UCMM), 500 bytes for connected messages (using ForwardOpen()), 4002 bytes for large connected messages (using ForwardOpenLarge())

**Comment by MiguelValentine** [comment]
#9

**Comment by lly-c232733** [comment]
Actually I didn’t fix it
